# Assignment 1: Mastering NumPy and Pandas for Data Analysis

###Objective:

The objective of this assignment is to help students learn and master the basic and advanced functionalities of NumPy and Pandas. These two libraries are fundamental for data manipulation, scientific computing, and data analysis, which are key skills for machine learning tasks.

By the end of this assignment, you will have hands-on experience working with arrays, data frames, and series, performing data manipulation, transformation, and statistical analysis, which will serve as the foundation for more complex tasks in machine learning.

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Part 1: NumPy Basics and Advanced Operations

###1.1 Basic Array Operations

Create a 1D NumPy array of integers from 0 to 9.

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 2D array of shape (2,5).



In [6]:
reshaped_arr = arr.reshape(2, 5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Perform element-wise addition, subtraction, multiplication, and division between this array and a scalar value (e.g., 2).

In [7]:
addition = reshaped_arr + 2
addition

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [8]:
subtraction = reshaped_arr - 2
subtraction

array([[-2, -1,  0,  1,  2],
       [ 3,  4,  5,  6,  7]])

In [9]:
multiplication = reshaped_arr * 2
multiplication

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [10]:
division = reshaped_arr / 2
division

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

Extract the 2nd row and the 3rd column of the reshaped array.

In [12]:
second_row = reshaped_arr[1, :]
second_row

array([5, 6, 7, 8, 9])

In [13]:
third_column = reshaped_arr[:, 2]
third_column

array([2, 7])

Compute the sum, mean, and standard deviation of all elements in the array.

In [14]:
sum_value = reshaped_arr.sum()
mean_value = reshaped_arr.mean()
std_dev = reshaped_arr.std()

sum_value, mean_value, std_dev

(45, 4.5, 2.8722813232690143)

###1.2 Advanced NumPy Operations

Create a 5x5 array of random integers between 1 and 100.

In [15]:
random_array = np.random.randint(1, 101, (5, 5))
random_array

array([[ 68,  18,  78,  73,   4],
       [ 94,   4,  57,  30,  83],
       [ 84,  26, 100,  28,  16],
       [ 41,  14,  84,  85,  78],
       [ 97,  50,  24,  82,   8]])

Find the maximum and minimum values in the array, along with their indices.

In [18]:
max_value, min_value = random_array.max(), random_array.min()
max_value, min_value

(100, 4)

Extract a sub-array of 3x3 from the center of the array.

In [20]:
center_index = random_array.shape[0] // 2
sub_array = random_array[center_index - 1:center_index + 2, center_index - 1:center_index + 2]
sub_array

array([[  4,  57,  30],
       [ 26, 100,  28],
       [ 14,  84,  85]])

Perform element-wise operations (addition, subtraction, etc.) between two NumPy arrays of the same shape.

In [24]:
array1, array2 = np.random.randint(1, 50, (5, 5)), np.random.randint(1, 50, (5, 5))
elementwise_sum = array1 + array2
elementwise_subtraction = array1 - array2
elementwise_multiplication = array1 * array2
elementwise_division = array1 / array2

elementwise_sum, elementwise_subtraction, elementwise_multiplication, elementwise_division

(array([[61, 44, 57, 62, 62],
        [81, 43, 28, 30, 66],
        [44, 63, 49, 65, 43],
        [69, 44, 59, 83, 82],
        [75, 38, 58, 29, 61]]),
 array([[ 29, -26, -19, -24, -36],
        [  3, -25,  24,  24, -28],
        [ 14, -21, -19,  17,  37],
        [ 21,  22,   7,   3, -14],
        [-15,   2, -12,  19, -15]]),
 array([[ 720,  315,  722,  817,  637],
        [1638,  306,   52,   81,  893],
        [ 435,  882,  510,  984,  120],
        [1080,  363,  858, 1720, 1632],
        [1350,  360,  805,  120,  874]]),
 array([[ 2.8125    ,  0.25714286,  0.5       ,  0.44186047,  0.26530612],
        [ 1.07692308,  0.26470588, 13.        ,  9.        ,  0.40425532],
        [ 1.93333333,  0.5       ,  0.44117647,  1.70833333, 13.33333333],
        [ 1.875     ,  3.        ,  1.26923077,  1.075     ,  0.70833333],
        [ 0.66666667,  1.11111111,  0.65714286,  4.8       ,  0.60526316]]))

Use boolean indexing to filter out values greater than 50 in the random array.

In [25]:
filtered_values = random_array[random_array > 50]
filtered_values

array([ 68,  78,  73,  94,  57,  83,  84, 100,  84,  85,  78,  97,  82])

###1.3 Broadcasting in NumPy

Create a 5x1 column vector (array) and add it to a 5x5 matrix using broadcasting.

In [26]:
column_vector = np.arange(5).reshape(5, 1)
column_vector

array([[0],
       [1],
       [2],
       [3],
       [4]])

Subtract a 1D array (size 5) from each row of a 5x5 matrix using broadcasting.

In [34]:
matrix = np.random.randint(1, 10, (5, 5))
broadcasted_subtraction = column_vector - matrix

broadcasted_subtraction

array([[-2, -2, -8, -7, -4],
       [-2, -6, -7, -4,  0],
       [-4, -2,  0,  1, -3],
       [ 1,  1,  1,  2, -3],
       [ 1, -5,  0, -1, -1]])

Demonstrate how to use broadcasting to calculate the Euclidean distance between two points in a 2D space (use array-based operations for this).

In [28]:
point1, point2 = np.array([2, 3]), np.array([5, 7])
euclidean_distance = np.sqrt(((point1 - point2) ** 2).sum())

euclidean_distance

5.0

###1.4 Matrix Operations

Create two 3x3 matrices and compute the dot product (matrix multiplication) of the two matrices.

In [29]:
matrix1, matrix2 = np.random.randint(1, 10, (3, 3)), np.random.randint(1, 10, (3, 3))

matrix_multiplication = np.dot(matrix1, matrix2)

matrix_multiplication

array([[119, 147, 101],
       [136, 156, 112],
       [133, 144,  97]])

Calculate the transpose of a matrix and explain the result.

In [30]:
transpose = matrix1.T

transpose

array([[8, 4, 1],
       [4, 8, 8],
       [7, 8, 9]])

Compute the inverse of a square matrix and explain when an inverse exists.

In [32]:
inverse_matrix = np.linalg.inv(matrix1) if np.linalg.det(matrix1) != 0 else 'Not invertible'

inverse_matrix

array([[ 0.06666667,  0.16666667, -0.2       ],
       [-0.23333333,  0.54166667, -0.3       ],
       [ 0.2       , -0.5       ,  0.4       ]])

# Part 1 DONE!!!!